print("    |\_")
print("   /  .\_ ")
print("  |   ___)")
print("  |    \ ")
print("  |  =  |")
print("  /_____\ ")
print(" [_______]")
print("    |\_")
print("   /  .\_ ")
print("  |   ___)")
print("  |    \ ")
print("  |  =  |")
print("  /_____\ ")
print(" [_______]")
print("    |\_       |\_")
print("   /  .\_    /  .\_ ")
print("  |   ___)  |   ___)")
print("  |    \    |    \ ")
print("  |  =  |   |  =  |")
print("  /_____\   /_____\ ")
print(" [_______] [_______]")
